In [22]:
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
from sklearn.cluster import KMeans
from sklearn import metrics
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

In [23]:
jobdata = pd.read_csv("data/jobs_in_data_2024.csv")

In [24]:
jobdata.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,work_setting,company_location,company_size,job_category
0,2024,Entry-level,Freelance,Applied Data Scientist,30000,USD,30000,United Kingdom,Remote,United Kingdom,M,Data Science and Research
1,2024,Executive,Full-time,Business Intelligence,230000,USD,230000,United States,In-person,United States,M,BI and Visualization
2,2024,Executive,Full-time,Business Intelligence,176900,USD,176900,United States,In-person,United States,M,BI and Visualization
3,2024,Senior,Full-time,Data Architect,171210,USD,171210,Canada,In-person,Canada,M,Data Architecture and Modeling
4,2024,Senior,Full-time,Data Architect,92190,USD,92190,Canada,In-person,Canada,M,Data Architecture and Modeling
5,2024,Mid-level,Full-time,Data Science,46203,GBP,57753,United Kingdom,In-person,United Kingdom,M,Data Science and Research
6,2024,Mid-level,Full-time,Data Science,38280,GBP,47850,United Kingdom,In-person,United Kingdom,M,Data Science and Research
7,2024,Entry-level,Full-time,Insight Analyst,50000,USD,50000,United States,Remote,United States,M,Data Analysis
8,2024,Entry-level,Full-time,Insight Analyst,40000,USD,40000,United States,Remote,United States,M,Data Analysis
9,2024,Senior,Full-time,Data Engineer,276000,USD,276000,United States,In-person,United States,M,Data Engineering

In [25]:
jobdata.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
work_setting          0
company_location      0
company_size          0
job_category          0
dtype: int64

In [26]:
jobdata2 = jobdata[['salary_in_usd', 'experience_level', 'employment_type', 'job_category', 'work_setting']]

In [27]:
jobdata_regression = pd.get_dummies(jobdata2, drop_first=True, columns = ['experience_level', 'employment_type', 'job_category', 'work_setting'])

In [28]:
jobdata_regression.head()

,salary_in_usd,experience_level_Executive,experience_level_Mid-level,experience_level_Senior,employment_type_Freelance,employment_type_Full-time,employment_type_Part-time,job_category_Cloud and Database,job_category_Data Analysis,job_category_Data Architecture and Modeling,job_category_Data Engineering,job_category_Data Management and Strategy,job_category_Data Quality and Operations,job_category_Data Science and Research,job_category_Leadership and Management,job_category_Machine Learning and AI,work_setting_In-person,work_setting_Remote
0,30000,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True
1,230000,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False
2,176900,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False
3,171210,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,True,False
4,92190,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,True,False

In [29]:
X = jobdata_regression[['experience_level_Executive',
       'experience_level_Mid-level', 'experience_level_Senior',
       'employment_type_Freelance', 'employment_type_Full-time',
       'employment_type_Part-time', 'job_category_Cloud and Database',
       'job_category_Data Analysis',
       'job_category_Data Architecture and Modeling',
       'job_category_Data Engineering',
       'job_category_Data Management and Strategy',
       'job_category_Data Quality and Operations',
       'job_category_Data Science and Research',
       'job_category_Leadership and Management',
       'job_category_Machine Learning and AI', 'work_setting_In-person', 'work_setting_Remote']]
y = jobdata_regression['salary_in_usd']

regressor = LinearRegression()
regressor.fit(X,y)

LinearRegression()

In [30]:
regressor.intercept_

np.float64(25234.14827985823)

In [31]:
jobdata_coef = pd.DataFrame(regressor.coef_, X.columns, columns=['Coefficient'])
jobdata_coef['Coefficient'] = jobdata_coef['Coefficient'].map(lambda x: f"-${abs(x):,.2f}" if x < 0 else f"${x:,.2f}")
jobdata_coef

                                             Coefficient
experience_level_Executive                    $86,758.24
experience_level_Mid-level                    $20,097.69
experience_level_Senior                       $53,832.35
employment_type_Freelance                    -$65,822.90
employment_type_Full-time                     $12,925.57
employment_type_Part-time                    -$16,968.86
job_category_Cloud and Database               $20,371.15
job_category_Data Analysis                   -$11,504.45
job_category_Data Architecture and Modeling   $21,816.03
job_category_Data Engineering                 $18,370.83
job_category_Data Management and Strategy    -$16,925.97
job_category_Data Quality and Operations     -$23,569.52
job_category_Data Science and Research        $35,016.51
job_category_Leadership and Management        $13,754.78
job_category_Machine Learning and AI          $52,510.51
work_setting_In-person                        $48,817.30
work_setting_Remote                           $41,367.64